[tool.poetry]
name = "playdjango"
version = "0.1.0"
description = ""
authors = ["Shih-Tse Chang <stchang@cs.nycu.edu.tw>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
